### PR TITLE
Make failing tests fail and fixing them

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
In general please wait for a review. I'm happy to fix merge conflicts or make minor PR fixes if asked so that you don't have to wait a cycle. I don't think any of these were super urgent.

**Comment by robertbastian** [comment]
I have a PR based on three of these.

**Comment by Manishearth** [comment]
Okay, still. At the very least please explain the situation.

On diplomat I'm fine with not requiring stamps for post-review commits and stuff, but I'd like to try to at least attempt to avoid doing this. All PRs on Diplomat will be conflicting because of codegen but fixing merge conflicts is super easy since you just rerun generation.

I recently waited two weeks for two gnarly interdependent PRs to land, and it was fine. Git is decent at supporting this kind of thing, even if GitHub isn't good at enabling reviews of them. What I tend to do is try and use well-separated commits for the later PRs.

**Comment by robertbastian** [comment]
This conflicted in more than just generated code, and this is not a gnarly PR.

**Comment by Manishearth** [comment]
> This conflicted in more than just generated code, and this is not a gnarly PR.

Yes, I'm suggesting you do them as stacked PRs, and the fact that this _isn't_ gnarly is a good indicator as to why stacking PRs should be even _easier_ here than the ones I was making.

Like, I really don't see the rush here.

**Comment by Manishearth** [comment]
I think this applies doubly so for PRs that I didn't even know were coming in, I'd be a bit more amenable to "I'm working on these things and here are some slam dunk obvious fixes I'm making, can I just merge them".

At times I have been like "@sffc can I merge this now and deal with the followups later" as well and that's worked out well. I get that the timezone difference makes this trickier but I'd like to limit this happening without warning, and if it is happening at least include an explanation as to why and either that you think the PR is uncontroversial or that you plan to handle review fixes later.

**Comment by robertbastian** [comment]
Tests were broken (by #538) and I fixed them while nobody was available to review. Sue me.

**Comment by sffc** [comment]
In the context of this specific PR, I don't see anything wrong with @robertbastian merging the configuration fix (the missing `--fail-on-error`) and the corresponding code fix, given that the change was small and only affected a few output files. If the fix were bigger, it might have been worth waiting for a review, but the fix was so small that a post-review seems okay to me in this particular instance.

**Pull request merged**
