### PR TITLE
Add `Mutability` enum

### PR DESCRIPTION
**Pull request by QnnOkabayashi**
Currently, we use `bool` to indicate mutability, and we end up with things like
```rust
match &param.ty {
    ast::TypeName::StrReference(/* mutable */ true) => { ... },
    // ...
}
```
This is bad because without the comment, it's not clear what `true` refers to. And the comment looks gross.

This PR introduces the `ast::Mutability` enum type so that we can express intent through the type system. It's definition is very simple:
```rust
pub enum Mutability {
    Mut,
    Const,
}
```
This makes examples like above much more readable:
```rust
match &param.ty {
    ast::TypeName::StrReference(ast::Mutability::Mut) => { ... },
    // ...
}
```

### CODE REVIEW

**Review by robertbastian — CHANGES_REQUESTED** [review]
`const` in Rust means more than 'immutable', using it as 'not mut' is confusing.

**Comment by QnnOkabayashi** [comment]
> `const` in Rust means more than 'immutable', using it as 'not mut' is confusing.

True, I'm open to ideas for how this should be named. `Mutability::Mutable`/`Mutability::Immutable`? `Mutable::True`/`Mutable::False`? We should also consider that it's used in `/tool` for stuff like C, where `const` means immutable, and no keyword means mutable, like in the following:
```rust
// tool/src/c/struct.rs, line 83

match mutable {
    ast::Mutability::Mut => "",
    ast::Mutability::Const => "const ",
}
```
So it's not used only in the context of Rust code.

**Comment by robertbastian** [comment]
The `ast` types represent the Rust code in `#[diplomat::bridge]`, so they should use Rust terminology. I don't think `Mutable` is great because enum names are supposed to be nouns, `Mutability::Mutable`/`Mutability::Immutable` are probably best.

**Comment by Manishearth** [comment]
Yeah the typical convention for this is `Mutability::Immutable` (or `Immut` if you want to be short)

**Comment by QnnOkabayashi** [comment]
Ok, now we have
```rust
pub enum Mutability {
    Mutable,
    Immutable,
}
```
Since this is also longer to type out (`ast::Mutability::Immutable` is a lot to type), I added `Mutability::is_{mutable,immutable}` methods to reduce the cognitive load that `if let` and `match` statements would involve using the longer name.

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
