### PR TITLE
Generate C++ code docs

### PR DESCRIPTION
**Pull request by gregtatum**
My editor will present documentation as tooltips when I hover C++ classes. It would be nice for the documentation to be propagated to the header files. This PR does that. Each commit should be well-formed for review. I did include one drive-by with some comments I wrote as I was getting oriented in the code.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
Should we add some docs to `example/` too? Not everywhere, just enough for the end-to-end test

**Comment by Manishearth** [comment]
Oh, we already have those, you just need to regen it to make CI pass.

**Comment by gregtatum** [comment]
Ah yes, I re-generated the examples, and caught a bug in the generated docs too.

**Comment by Manishearth** [comment]
Thanks!

**Pull request merged**
