### PR TITLE
Struct Object Constructors

### LINKED ISSUE #719: JS2 constructors: Struct ctors should take an object, not a list of fields
Structs should be constructable via `new Struct({field1: 1, field2: "foo"})`, without using ordered parameters.

### PR DESCRIPTION
**Pull request by ambiguousname**
Fixes #719.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
much nicer, thanks!!

**Comment by Manishearth** [comment]
In particular I appreciate moving the from-ffi logic out of the constructor and making it purely internal. Good call.

**Comment by ambiguousname** [comment]
Something to test: JS tests are passing on the CI, but not on my machine

**Review by Manishearth — APPROVED** [review]

**Comment by ambiguousname** [comment]
Uh oh. Don't have a lot of time to test right now, but @Manishearth looks like there's a bug in the padding logic.

But it seems not to be an issue on the CI?

Here's the error I get:

```
  Error {
    message: `wasm panicked at feature_tests\\src\\structs.rs:233:13:␊
    assertion \`left == right\` failed␊
      left: 0␊
     right: 414`,
  }
```

And if I adjust the following line in `ScalarPairWithPadding.mjs`:
```
_intoFFI(
        functionCleanupArena,
        appendArrayMap,
        forcePadding
    ) {
        return [this.#first, ...diplomatRuntime.maybePaddingFields(forcePadding, 3 /* x i8 */), this.#second]
    }
```

So that there is *no* padding, then no error is returned and all assertions pass. I'm not sure what the difference is between the CI and my machine is, except maybe the WASM target version? I'll have to do some digging on this though when I have time.

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
@ambiguousname does main fail for you too, locally?

I think we just run on latest stable on CI, and on MSRV. Maybe nightly changed something

**Comment by ambiguousname** [comment]
It could be something to do with nightly? I'll have to look into it when I have some more time.

**Comment by ambiguousname** [comment]
This is really strange. After uninstalling a bunch of toolchains and switching my default toolchain a few times, the error is totally gone. Even when setting it back to the default toolchain I was using before.

Weird! It's fixed now though, so I think we're okay.

**Comment by Manishearth** [comment]
Hmm, I'm also having trouble reproducing it

**Comment by ambiguousname** [comment]
I figured out what's causing it. New issue: #725

**Pull request merged**
