### PR TITLE
Introduce `DiplomatChar`

### LINKED ISSUE #318: Provide something other than `char` for FFI
`char` isn't actually ABI-defined (and improper_ctypes complains about it). We should use some wrapper around uint32_t at the ABI level

### PR DESCRIPTION
**Pull request by robertbastian**
Fixes #318

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
Why did you do `type DiplomatChar = u32` instead of `struct DiplomatChar(pub u32)` ?

**Comment by robertbastian** [comment]
This type goes on the ABI, and `struct DiplomatChar(pub u32)` is not generally ABI compatible with `u32`

**Comment by sffc** [comment]
Ok. It just struck me as slightly weird because `type` means that the things are 100% equivalent and can be swapped out at will, but in this case `DiplomatChar` actually has different semantics than `char` because we read it in a proc macro in a layer above Rust code compilation.

**Comment by robertbastian** [comment]
The typedef is basically a signal to the macro to treat this as a char (i.e. generate `uchar32_t` instead of `uint32_t` in C), and a signal to the Rust implementation that this is meant to be a char.

I could have actually done `pub struct DiplomatChar(pub u32)` and have the macro wrap and unwrap, but:
* that's extra complexity in the macro
* it's nice that Rust code can just pass this type to `...32` methods without having `.0` everywhere
* it's nice that Rust code can use primitive casts with it, i.e. a suffixed `as DiplomatChar` instead of `DiplomatChar(` at the beginning of the expression

**Comment by sffc** [comment]
Okay or point 1. Neutral on point 2. On point 3, I don't generally like `as` casts in Rust because they hide away footguns like converting signed to unsigned and converting larger ints to smaller ints. I find `DiplomatChar(` less error-prone (and it is even a few characters shorter).

**Pull request merged**
