### PR TITLE
Symbol Constructors

### PR DESCRIPTION
**Pull request by ambiguousname**
Fix for #635 and #582.

Needs testing and I need to add support for opaque, but I'm breaking for the next few hours, so I'll be back to work on this later.

### CODE REVIEW

**Comment by ambiguousname** [comment]
Should wait to merge #643 before this (I can update some tests to verify functionality once #643 is merged)

**Comment by ambiguousname** [comment]
Updated to account for #643, ready to merge

**Review by Manishearth — APPROVED** [review]
nice!

**Comment by Manishearth** [comment]
would be cool to support default ctors on opaques this same way.

(and structs, too, where if you define a default ctor then the from-field ctor becomes a method or something)

**Pull request merged**
