### PR TITLE
Add explicit keyword for generated constructor

### PR DESCRIPTION
**Pull request by makotokato**
https://bugzilla.mozilla.org/show_bug.cgi?id=1868324

I would like to add explicit keyword to generated C++ constructor.

### CODE REVIEW

**Comment by robertbastian** [comment]
Is this a breaking change for existing clients?

**Comment by makotokato** [comment]
[Our coding style](https://firefox-source-docs.mozilla.org/code-quality/coding-style/coding_style_cpp.html) needs `explicit` keyword for non copy/move constructor.  So we have to modify it to use icu_capi since current FFI API doesn't accept our rule. `explicit` keyword can prevent unexpected conversion.

Also, see https://github.com/rust-diplomat/diplomat/issues/349 for diplomat_runtime.hpp.

**Comment by robertbastian** [comment]
I understand the problem. My question is, can this change *break compilation* for anyone who is using ICU4X today?

**Comment by Manishearth** [comment]
It depends on whether you consider the raw pointer API to be actually public. I don't but we should talk about it.

**Comment by makotokato** [comment]
I don't think adding explicit keyword breaks existed code. But feel free to reject this PR.

**Comment by Manishearth** [comment]
It is for anyone using the constructor implicitly. I think that's not a big deal though, because that constructor is a major footgun.

**Comment by Manishearth** [comment]
@sffc mind checking and fixing this in CPP2?

**Pull request merged**
